[theme]
base = "dark"
primaryColor = "#DC143C"
backgroundColor = "#0E0E0E"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 10

[browser]
gatherUsageStats = false

[ui]
hideTopBar = false
hideSidebarNav = false

[runner]
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"
