[theme]
primaryColor = "#DC143C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 10

[browser]
gatherUsageStats = false

[ui]
hideTopBar = false
hideSidebarNav = false

[runner]
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"
