# This file contains sensitive information
# DO NOT commit this file to version control

# Password for accessing the application
password = "SWT4545"

# Google Maps API Key (optional)
# Get your API key from: https://console.cloud.google.com/apis/credentials
# Enable the Distance Matrix API for your project
GOOGLE_MAPS_API_KEY = "AIzaSyBT9M_urwRYy_emWh_arrx6CzSXXFfiS_w"